title: Ben and Esther Rosenbloom Maryland Hillel Center
email:
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  load_paths:
    - _sass
    - node_modules

# IMPORTANT - Not very intuitive but this is how to get node_modules to work - Ty
exclude: []
